#ifndef CONFIG
#define CONFIG

#define CHIP8_WINDOW_TITLE "Chip8"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_WINDOW_SCALER 10
#define CHIP8_REGISTER_AMOUNT 16
#define CHIP8_STACK_SIZE 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_CHARACTER_SET_ADDRESS 0x00
#define CHIP8_LOAD_ADDRESS 0x200
#define CHIP8_DEFAULT_SPRITE_HEIGHT 5

#endif
